import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import Qna from '../components/Qna'
import qnadata from '../components/qnadata'
import Navbar from '../components/Navbar'


const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* FONTS */}
        <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet" />

        {/* KATEX JS FILES */}
        {/* <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossOrigin="anonymous"></script> */}
        {/* <script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossOrigin="anonymous" onLoad="window.renderMathInElement(document.body)" ></script> */}
      </Head>

      <Navbar />
      {qnadata.map((val, index) => {
        console.log(index);

        return (
          <>
          {/* replace \ with \\ in the data object */}
            <Qna question={val.question} qnimg={val.qnimg} answer={val.answer} />
          </>

          
        );
      })}



      {/* BOOTSTRAP JS */}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossOrigin="anonymous" strategy="lazyOnload" />

    </div>
  )
}

export default Home


